config/routes.rb
Portal::Application.routes.draw do
  
  resources :rants


  get '/home' => 'pages#index', :as => 'home'

end

app/models/rant.rb
class Rant < ActiveRecord::Base
  attr_accessible :message, :title, :image, :remote_image_url

  mount_uploader :image, ImageUploader
end

app/models/tweet.rb
require 'grackle'

class Tweet < ActiveRecord::Base
  attr_accessible :created, :message


  	def self.update_tweets
		client = Grackle::Client.new(:auth=>{
		  :type=>:oauth,
		  :consumer_key=> ENV["CONSUMER_KEY"], :consumer_secret=> ENV["CONSUMER_SECRET"],
		  :token=> ENV["TOKEN"], :token_secret=> ENV["TOKEN_SECRET"]
		})


		if client.users.show? :screen_name=>'bretthoyer' #http://twitter.com/users/show.json?screen_name=some_user
			tweets = client.statuses.user_timeline? :screen_name => 'bretthoyer', :count => 5
			tweets.each do |tweet|
			  created = DateTime.parse(tweet.created_at)
			  unless Tweet.exists?(["created=?", created])
			  Tweet.create({:message => tweet.text, :created => created })	
			  end
			end

		end
	end


	def readable_datetime
		self.created.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%y %I:%M%p")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@tweets = Tweet.find(:all, :order=> 'id desc', :limit => 5).reverse
		@rants = Rant.all
	end



end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  # GET /rants
  # GET /rants.json
  def index
    @rants = Rant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rants }
    end
  end

  # GET /rants/1
  # GET /rants/1.json
  def show
    @rant = Rant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rant }
    end
  end

  # GET /rants/new
  # GET /rants/new.json
  def new
    @rant = Rant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rant }
    end
  end

  # GET /rants/1/edit
  def edit
    @rant = Rant.find(params[:id])
  end

  # POST /rants
  # POST /rants.json
  def create
    @rant = Rant.new(params[:rant])

    respond_to do |format|
      if @rant.save
        format.html { redirect_to @rant, notice: 'Rant was successfully created.' }
        format.json { render json: @rant, status: :created, location: @rant }
      else
        format.html { render action: "new" }
        format.json { render json: @rant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rants/1
  # PUT /rants/1.json
  def update
    @rant = Rant.find(params[:id])

    respond_to do |format|
      if @rant.update_attributes(params[:rant])
        format.html { redirect_to @rant, notice: 'Rant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rants/1
  # DELETE /rants/1.json
  def destroy
    @rant = Rant.find(params[:id])
    @rant.destroy

    respond_to do |format|
      format.html { redirect_to rants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="background-overlay">
	<div class="initials-logo"></div>

	<h3 class="twitter-header">@BrettHoyer</h3>	
	<ul>
		<% @tweets.each do |tweet| %>
		<div class="tweet-container row-fluid">
			<i class="icon-twitter icon-2x"></i>
			<span class="tweet-datetime"><%= tweet.readable_datetime %></span>
		<li><%= tweet.message %></li>
		</div>	

		<% end %>
	</ul>

	<% @rants.each do |rant| %>
	<h4><%= rant.title %></h4>
	<%= image_tag rant.image_url(:thumb).to_s %>
	<p><%= rant.message %></p>
	<% end %>

</div>

app/views/rants/_form.html.erb
<%= form_for @rant, :html => {:multipart => true} do |f| %>
  <% if @rant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rant.errors.count, "error") %> prohibited this rant from being saved:</h2>

      <ul>
      <% @rant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL:" %><br />
    <%= f.file_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rants/edit.html.erb
<h1>Editing rant</h1>

<%= render 'form' %>

<%= link_to 'Show', @rant %> |
<%= link_to 'Back', rants_path %>

app/views/rants/index.html.erb
<h1>Listing rants</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rants.each do |rant| %>
  <tr>
    <td><%= rant.title %></td>
    <td><%= rant.message %></td>
    <td><%= link_to 'Show', rant %></td>
    <td><%= link_to 'Edit', edit_rant_path(rant) %></td>
    <td><%= link_to 'Destroy', rant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rant', new_rant_path %>

app/views/rants/new.html.erb
<h1>New rant</h1>

<%= render 'form' %>

<%= link_to 'Back', rants_path %>

app/views/rants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @rant.title %>
</p>

<p>
  <b>Message:</b>
  <%= @rant.message %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @rant.image_url(:thumb).to_s %>
</p>



<%= link_to 'Edit', edit_rant_path(@rant) %> |
<%= link_to 'Back', rants_path %>